INSERT INTO `category` (`category_id`, `category_name`) VALUES
(1, 'Sport'),
(2, 'Fruits'),
(3, 'Animals'),
(4, 'Coding'),
(5, 'Landscape'),
(6, 'Others');


INSERT INTO `tags` (`tag_title`) VALUES
('basketball'),
('biker'),
('birds'),
('candle'),
('cat'),
('containers'),
('covid'),
('dog'),
('driving'),
('gym'),
('laptop'),
('mac'),
('macbook'),
('motorcycle'),
('panic'),
('pineapple'),
('sea'),
('skateboard'),
('sunset'),
('swagg-pineapple'),
('text-editor'),
('woman'),
('young-boy'),
('untagged');


INSERT INTO `images` (`file_name`, `file_url`, `description`, `category_id`, `created_at`)
VALUES
  ("Man in red jumping", "http://localhost:8000/uploads/man-in-red-tank-top-jumping-on-obstacle-3763879.jpg", "", 1, NOW()),
  ("Man playing basketball", "http://localhost:8000/uploads/man-in-red-crew-neck-t-shirt-and-black-pants-sitting-on-4108004.jpg", "", 1, NOW()),
  ("Pineapple wearing sun glasses", "http://localhost:8000/uploads/pineapple-with-sunglasses-1189314.jpg", "", 2, NOW()),
  ("Top model swagg pineapple", "http://localhost:8000/uploads/green-pineapple-fruit-with-brown-framed-sunglasses-beside-1161547.jpg", "", 2, NOW()),
  ("Young boy in jacket", "http://localhost:8000/uploads/young-boy-in-jacket-holding-white-flower-pot-3771640.jpg", "", 6, NOW()),
  ("Cat with blue eyes", "http://localhost:8000/uploads/adorable-animal-cat-cat-s-eyes-357141.jpg", "", 3, NOW()),
  ("Brown cat", "http://localhost:8000/uploads/adult-brown-tabby-cat-747795.jpg", "", 3, NOW()),
  ("Don't panic dude", "http://localhost:8000/uploads/don-t-panic-text-on-tissue-paper-3991793.jpg", "", 6, NOW()),
  ("Dog standing near people", "http://localhost:8000/uploads/dog-standing-near-people-and-vehicle-1870642.jpg", "", 3, NOW()),
  ("Laptop office and coding", "http://localhost:8000/uploads/laptop-office-internet-technology-177598.jpg", "", 4, NOW()),
  ("Abstract business code", "http://localhost:8000/uploads/abstract-business-code-coder-270348.jpg", "", 4, NOW()),
  ("People swimming on the beach", "http://localhost:8000/uploads/silhouette-photography-of-people-swimming-on-the-beach-681617.jpg", "", 5, NOW()),
  ("Flock of birds", "http://localhost:8000/uploads/flock-of-birds-2373357.jpg", "", 3, NOW()),
  ("Two white birds", "http://localhost:8000/uploads/two-white-birds-2009775.jpg", "", 3, NOW()),
  ("Taking photo of skate park", "http://localhost:8000/uploads/photo-of-skate-park-during-dawn-3006222.jpg", "", 1, NOW()),
  ("Man skateboarding", "http://localhost:8000/uploads/photo-of-man-skateboarding-3581981.jpg", "", 1, NOW()),
  ("Man doing tricks with skateboard", "http://localhost:8000/uploads/man-doing-tricks-on-a-skateboard-1984121.jpg", "", 1, NOW()),
  ("Export business containers", "http://localhost:8000/uploads/business-commerce-container-export-379964.jpg", "", 6, NOW()),
  ("Driving on sandy stadium", "http://localhost:8000/uploads/person-driving-dirt-motorcycle-on-sandy-stadium-1130857.jpg", "", 1, NOW()),
  ("Motorbike running", "http://localhost:8000/uploads/motor-bike-running-close-up-photography-2519374.jpg", "", 1, NOW()),
  ("Biker championship", "http://localhost:8000/uploads/action-bike-biker-championship-572468.jpg", "", 1, NOW()),
  ("Apple devices", "http://localhost:8000/uploads/access-apple-apple-devices-apple-keyboard-370470.jpg", "", 6, NOW()),
  ("Macbook pro screen", "http://localhost:8000/uploads/macbook-pro-3260626.jpg", "", 6, NOW()),
  ("Woman holding candle", "http://localhost:8000/uploads/woman-holding-disposable-lighter-1342650.jpg", "", 6, NOW());

INSERT INTO `assoc_tags_images`(`image_id`, `tag_name`) 
VALUES
  (1, 10),
  (2, 1),
  (3, 16), (3, 20),
  (4, 16),
  (4, 20),
  (5, 23),
  (6, 5), (6, 5),
  (7, 15),
  (8, 8),
  (9, 11), (9, 12), (9, 13), (9, 21),
  (10, 21),
  (11, 24),
  (12, 24),
  (13, 24),
  (14, 24),
  (15, 24),
  (16, 24),
  (17, 24),
  (18, 24),
  (19, 24),
  (20, 24),
  (21, 24),
  (22, 24),
  (23, 24),
  (24, 24);